[package]
name = "bevy_serialization_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
bevy_rapier3d = "0.23"
rapier3d = "0.17.2"
glam = "0.25"
ron = "0.8"
moonshine-save = "0.3.4"
bevy_egui = "0.24"
egui = "0.24"
egui_extras = "0.24"
urdf-rs = "0.8.0"
multimap = "0.9.1"
strum = "0.25"
strum_macros = "0.25"
bitflags = "2.4.1"
nalgebra = "0.32"
#serde = "1.0.*"
yaserde = "0.9"
derive_more = "0.99"
bitvec = "*"
bevy_obj = "0.12"
log = "*"
bevy_camera_extras = "*"

[dev-dependencies]
bevy = {version = "0.12", features = ["dynamic_linking"]}
bevy_ui_extras = "0.3"
bevy-inspector-egui = "0.22.0"
